// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW64JkJ1J4ABcLp0_a0U90yE9T330f630',
    appId: '1:1014087703295:web:5d8ab70be93d00c4bf4aca',
    messagingSenderId: '1014087703295',
    projectId: 'cbl-mobile-sync-auth',
    authDomain: 'cbl-mobile-sync-auth.firebaseapp.com',
    storageBucket: 'cbl-mobile-sync-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMnmZucfg6iOOPqM-6vzrP7aH950LjiCQ',
    appId: '1:1014087703295:android:89979c962018c320bf4aca',
    messagingSenderId: '1014087703295',
    projectId: 'cbl-mobile-sync-auth',
    storageBucket: 'cbl-mobile-sync-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9nxg9-c50GLcXSSzFwzPXtLxUfIunB0E',
    appId: '1:1014087703295:ios:71f6adc5856aed30bf4aca',
    messagingSenderId: '1014087703295',
    projectId: 'cbl-mobile-sync-auth',
    storageBucket: 'cbl-mobile-sync-auth.appspot.com',
    iosClientId: '1014087703295-h3tclgar7eb17s7m7c0ge5ntggomsmjn.apps.googleusercontent.com',
    iosBundleId: 'com.example.cbl-mobile-sync-auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9nxg9-c50GLcXSSzFwzPXtLxUfIunB0E',
    appId: '1:1014087703295:ios:5ee6518fb4d3eeccbf4aca',
    messagingSenderId: '1014087703295',
    projectId: 'cbl-mobile-sync-auth',
    storageBucket: 'cbl-mobile-sync-auth.appspot.com',
    iosClientId: '1014087703295-s67ltosnqnfm90gptta4q2veqcmj0s3t.apps.googleusercontent.com',
    iosBundleId: 'com.example.cbl-mobile-sync-auth.macos',
  );
}
